### ISSUE TITLE
There is no such a word like childrens in english

### ISSUE THREAD

**Issue by cojack** [nestjsx/nest-router#106]
Plural version of child is children, so `childrens` is a linguistic error.

**Comment by shekohex** [comment]
yes, we just added it here for backwards compatibility and no breaking changes so far
https://github.com/nestjsx/nest-router/blob/master/src/utils/flat-routes.util.ts#L12
there's a warning ⚠️ tho if you used it.

also related to #6 and https://github.com/nestjsx/nest-router/blob/master/CHANGELOG.md#105---2018-02-27
