### ISSUE TITLE
Host / subdomain support

### ISSUE THREAD

**Issue by patie** [nestjsx/nest-router#12]
Is there planned support for host/subdomain?

**Comment by shekohex** [comment]
Hi @patie , actually this out of the scope of nest-router goal
the router module is just a simple function that take some configurations and add some `metadata` on every module, the other work goes in `nest/core`  it will also read that `metadata` and refactor the routes to it.

so back to your issue, until now there is no future plan to add support for vHosts/subdomains to this package.
but as nest is built in top of expressjs you could use one of these nice packages that do what you need:

https://github.com/expressjs/vhost
and the good docs for it: https://expressjs.com/en/resources/middleware/vhost.html
and also take a look at this nice one https://github.com/bmullan91/express-subdomain
