### ISSUE TITLE
Difference to nestjs RouterModule ?

### ISSUE THREAD

**Issue by elovin** [nestjsx/nest-router#136]
What is the difference of this module compared with the nestjs core RouterModule ?

So far both seem to work equally the only issue I encountered with the nestjs core RouterModule was that during e2e tests the mapping was lost when closing the app after each test, the same does not happen with the nestjsx RouterModule.

**Comment by shekohex** [comment]
Absolutely, there is no difference between this package and the one in the core, in fact, the code in the core is same. what happened is that we upstreamed this package code to be included into the core of Nestjs.

Back to the issue about e2e testing, I guess you should open an issue in nestjs repo.
