### ISSUE TITLE
Version in routes

### ISSUE THREAD

**Issue by bovandersteene** [nestjsx/nest-router#29]
When I want to do multiple versions on my routes, and I reuse a controller for certain version, it only takes the latest version.

```
const routes: Routes = [
  {
    path: 'v1',
    children: [
      {
        path: Route.COMIC,
        module: ComicModule,
      },
      {
        path: Route.MY_COLLECTION,
        module: MyCollectionModule,
      },
    ],
  },
  {
    path: 'v2',
    children: [
      {
        path: Route.COMIC,
        module: ComicModule,
      },
      {
        path: Route.MY_COLLECTION,
        module: MyCollectionModule,
      },
    ],
  },
];
```

gives 
![image](https://user-images.githubusercontent.com/1673799/46171315-76e3da00-c2a0-11e8-85c5-51e4184ded9e.png)

So I miss, the v1 mapping

**Comment by shekohex** [comment]
it the obvious result as any `Controller` or `Module` should have only a single route. with that have said,

expressjs supports [routes alias](https://expressjs.com/en/4x/api.html#app.get.method)  as an [array](https://expressjs.com/en/4x/api.html#path-examples) 

so we can use 
```js
app.get(['/user/:id', '/profile/:id'], (req, res) => { ... });
```
as nest-router uses the build-in `MODULE_PATH` which is provided in [nestjs/core](https://github.com/nestjs/nest/blob/master/packages/core/router/routes-resolver.ts#L42)

we cannot provide it as an array.
so we have a workaround here:

you can create another module with the same name and post-fix it with v2 or whatever,
and also do that for your controller, actually you would not have to re implement the same methods of that controller you can extend it and override the changed API/method of the old method or create new one, nest should get the old methods too.

to be clear i'll make it as an example:

we have module `Users` and in that module we have one controller `UserPayment`

```ts
...
@Controller('/payment')
export class UserPayment {
    @Get(':id')
    async getUserPayments(@Parm('id') userId: number) {
        ...
        // some complex sql calls
    }
   ...
   // another methods
}
```
```ts
...
@Module({
    controllers: [UserPayment]
})
export class Users {}
```
then we have updated our api and now we have api v2

we will create another module `UsersV2` and another `UserPaymentV2` controller

```ts
...
@Controller('/payment')
export class UserPaymentV2 extends UserPayment {
    @Get(':id')
    async getUserPayments(@Parm('id') userId: number) {
        ...
        // some complex sql calls
       // with update for v2
    }
   ...
   // another methods from extended class
}
```
```ts
...
@Module({
    controllers: [UserPaymentV2]
})
export class UsersV2 {}
```
then in our routes
```ts
const routes: Routes = [
  {
    path: 'v1',
    children: [{ path: 'users', module: Users }],
  },
  {
    path: 'v2',
    children: [{ path: 'users', module: UsersV2 }],
  },
];
```
> PS: `children` array can be just an array of modules if they have the same path.

**Comment by vahidvdn** [comment]
@shekohex Do you think this is a good idea? Let say we will have 3 versions. In the user folder, there will be 3 files for each user.module.ts and user.controller.ts
Which seems very hard to maintain. Any idea?

**Comment by shekohex** [comment]
@vahidvdn so you have 3 versions of the same Controller?
The easiest way is that you every time you create a new version you extend the original Controller class and override/add any new methods you want.
And you version them in the routes file.

**Comment by vahidvdn** [comment]
@shekohex Thanks for the point.
What I mean was about managing files. Let say we will have module, moduleV2, and moduleV3. Also for controllers. It seems very messy.

**Comment by shekohex** [comment]
Did you tried to use the same Module, but with 3 Different Controllers?
ModuleA: ControllerV1, ControllerV2, ControllerV3

Every one of these extends the previous one with new changes and with a new route in the `@Controller()` 

Is that ok?

**Comment by vahidvdn** [comment]
@shekohex No, that's not. In your example:

```
const routes: Routes = [
  {
    path: 'v1',
    children: [{ path: 'users', module: Users }],
  },
  {
    path: 'v2',
    children: [{ path: 'users', module: UsersV2 }],
  },
];
```

In v2 path, you mentioned UsersV2 module. So, as I understand we can't have only one module. Am I right?

**Comment by shekohex** [comment]
Yes, any module will only have one version, but as many Controllers you wish, so I guess you could instead of using this package you could add the versions to the Controllers itself.

If you don't need to versioning based on the modules.
