### ISSUE TITLE
Nest Router with Swagger doesn't show correct routes

### ISSUE THREAD

**Issue by mentos1386** [nestjsx/nest-router#3]
If we use nest router with swagger module. Swagger module doesn't know the correct routes. Is it even possible to implement this?

**Comment by shekohex** [comment]
Hi @mentos1386 
the implementation of `Nest RouterModule`  was missing in `Swagger` Package.
 This PR https://github.com/nestjs/swagger/pull/54  will solve the problem. 
Thank again for reporting :heart:

**Comment by shekohex** [comment]
it is ok now
closing.

**Comment by alexvanzyl** [comment]
Thought this my be related.

I am having an  issue with swagger generating routes with regards to nested resource, for example if I have the following routes:
```
export const routes: Routes = [
  {
    path: '/ninja',
    module: NinjaModule,
    children: [
        { path: ':ninjaId/cats', module: CatsModule },
    ],
  },
];
```
The generated swagger document will generate the following route where `ninjaId` is the parent id:
```
GET ​/ninja​/:ninjaId​/cats
```
In order to work correctly with the swagger UI what it should generate is the below route (Notice the curly brackets):
```
GET ​/ninja​/{ninjaId​}/cats
```

Any ideas?

My dependencies are:
```
"dependencies": {
    "@nestjs/common": "^6.0.0",
    "@nestjs/core": "^6.0.0",
    "@nestjs/platform-express": "^6.0.0",
    "@nestjs/platform-fastify": "^6.0.1",
    "@nestjs/swagger": "^3.0.1",
    "class-transformer": "^0.2.0",
    "class-validator": "^0.9.1",
    "fastify-swagger": "^2.3.2",
    "nest-router": "^1.0.9",
    "nestjs-config": "^1.3.21",
    "reflect-metadata": "^0.1.12",
    "rimraf": "^2.6.2",
    "rxjs": "^6.3.3"
  },
  "devDependencies": {
    "@types/express": "^4.16.0",
    "@types/jest": "^23.3.13",
    "@types/node": "^10.12.18",
    "@types/supertest": "^2.0.7",
    "@nestjs/testing": "^6.0.0",
    "jest": "^23.6.0",
    "nodemon": "^1.18.9",
    "prettier": "^1.15.3",
    "supertest": "^3.4.1",
    "ts-jest": "^23.10.5",
    "ts-node": "^7.0.1",
    "tsconfig-paths": "^3.7.0",
    "tslint": "5.12.1",
    "typescript": "^3.2.4"
  },
```

**Comment by Joel-Raju** [comment]
I'm facing the same problem as @alexvanzyl

**Comment by shekohex** [comment]
@joel-Raju @alexvanzyl any minimal repository to reproduce that behavior? 
I will reopen that issue.

**Comment by Joel-Raju** [comment]
@shekohex checkout this example https://github.com/Joel-Raju/nest-router/tree/master/examples/heroes

see the endpoint generated by swagger for `/heroes/:heroId/powers`

**Comment by shekohex** [comment]
@Joel-Raju @alexvanzyl the hot fix is on its way https://github.com/nestjs/swagger/pull/253 :smiley:

**Comment by shekohex** [comment]
@Joel-Raju @alexvanzyl it dose not seem to be a hot fix at all :joy: , it just got merged now
please once a new version of `@nestjs/swagger` package get published, give it another try, so i can close this issue.

thanks :)

**Comment by DmytroMysak** [comment]
Still having the same issue:

router:
```export const routes: Routes = [
  {
    path: '/private',
    module: PrivateModule,
  },
  {
    path: '/public',
    module: PublicModule,
    children: [
      {
        path: '/notifications',
        module: NotificationModule,
      },
    ],
  },
];
```

In swagger ui I have /notifications API instead of /public/notificatons
![image](https://user-images.githubusercontent.com/22196591/75963499-47da8a80-5ece-11ea-94f5-fb757976ac63.png)

**Comment by steven274** [comment]
I have the same problem with DmytroMysak

**Comment by chriskuech** [comment]
@shekohex this appears to still be an issue

**Comment by francorosatti** [comment]
I'm facing the same issue, any workaround?

**Comment by francorosatti** [comment]
Hi @chriskuech 
> @shekohex this appears to still be an issue

I fix it by moving from the nest-router external package to the one included in @nestjs/core as explained in the readme of this project:
> As of Nestjs v8.0.0 This module got added into the @nestjs/core. see the [docs](https://docs.nestjs.com/recipes/router-module) with that being said, this package is still maintained (for now).
