### ISSUE TITLE
ValidationPipes don't seem to work for me after using this router.

### ISSUE THREAD

**Issue by Texlo-Dev** [nestjsx/nest-router#40]
Hi,
So I recently installed this router, and I am trying to use a validation pipe with my post routes to validate input. Unfortunately, when I set up the validation router, nothing seems to happen, and people can specify whatever values they want.
In this case, I request /test with a body of

`{ "string": true }`

I expect this to error but it does not.

**Minimal reproduction of the problem**
Test DTO

```js
import { IsString } from "class-validator";
export class TestDTO {
  @IsString() public readonly string: string;
}
```

Test Controller

```js
@Controller()
export class TestController {
  @Post("/test")
  public testing(@Body(new ValidationPipe()) test: TestDTO): string {
    return test.string;
  }
}
```

Are validationpipes different when using this router?

**Comment by shekohex** [comment]
Hi @RTK99 .
I think it's not a router problem, i updated the current example here:
https://github.com/shekohex/nest-router/blob/d7fae4f2b8b906bedaa737390ba8b4201853256d/examples/nest-v5x/src/cats/cats.controller.ts#L13-L17
https://github.com/shekohex/nest-router/blob/d7fae4f2b8b906bedaa737390ba8b4201853256d/examples/nest-v5x/src/cats/dto/create-cat.dto.ts#L1-L5
you can clone and play with.
the pipes and `ValidationPipe` works normally.
