### ISSUE TITLE
Slug route interferes with normal route

### ISSUE THREAD

**Issue by ghost** [nestjsx/nest-router#45]
Having my routes defined like this,
```ts
RouterModule.forRoutes([{
    path: 'posts',
    module: PostsModule,
    children: [
        {
            path: 'random',
            module: PostModule
        },
        {
            path: '/:postId(\\d+)/',
            module: PostModule
        }
    ]
}])
```
I'm able to access `/posts/2736`, but I'm not able to access `/posts/random`.
I tried changing the order of the child routes, but it resulted in not being able to access `/posts/2736` anymore.

It does work, however, when I define the routes directly inside the `PostsController`.
```ts
@Get('random')
findRandom() {
    return 'Random post.';
}

@Get(':postId(\\d+)')
findOne() {
    return 'Post by id.';
}
```

Any way to solve this? Thanks in advance!

**Comment by shekohex** [comment]
> Any way to solve this?

Unfortunately, you can't do this, the reason of this behavior is that every NestModule has it's own unique `path`. 
So Here 
```ts
children: [
  {
    path: 'random', // PostModule `path` is now `/posts/random`
    module: PostModule
   },
   {
      path: '/:postId(\\d+)/', // PostModule `path` is now `/posts/:postId(\\d+)/`
      module: PostModule
   }
]
``` 
I think you are using `nest-router` in such a way that isn't intended to be used in.
this package was created to solve some problems in organizing your modules.
so, as you said, it's better here to use `Controllers`.

Regards.
