### ISSUE TITLE
Route resolving fails when setGlobalPrefix() is used

### ISSUE THREAD

**Issue by jbjhjm** [nestjsx/nest-router#52]
Hi Shekohex, 
after some trial and error I think nest-router is having issues when a globalPrefix is set in bootstrap function.

Let's say my routes look like this:
```ts
const routes:Routes = [
	{
		path: '/test', 
		module: TestBackendModule
	}
];
```
Combined with this
```ts
async function bootstrap() {
	const app = await NestFactory.create(AppModule);
	app.setGlobalPrefix(`api`);
	await app.listen(3333);
}
```
Neither calls to /api/test nor calls to /test could be routed successfully.
After removing the call to setGlobalPrefix, calls to /test were routed to the TestBackendModule.
Is this behaviour intended? If so, may I recommend to add a note to the Readme.

**Comment by shekohex** [comment]
> Is this behaviour intended?

Nope, it's a bug in @nestjs/core, see this PR https://github.com/nestjs/nest/pull/1594 it should fix this issue

**Comment by jbjhjm** [comment]
> > Is this behaviour intended?
> 
> Nope, it's a bug in @nestjs/core, see this PR [nestjs/nest#1594](https://github.com/nestjs/nest/pull/1594) it should fix this issue

Ah I see, thanks!

**Comment by willcooley** [comment]
Is there a workaround to this? Only thing I can think of fixing nest's router, and keeping the package local until something is done. I'm in a tight squeeze to have this fixed by tomorrow. Any ideas? Is there anyway to override nest's router method for the fix to be used, instead of using what is currently there? I've lost a bunch of time trying to figure this out sadly, lol.

**Comment by shekohex** [comment]
For anyone need a hot fix try this https://github.com/shekohex/nest-router/issues/53#issuecomment-470527512 


Thanks to @willcooley for that solution 🎉

**Comment by shekohex** [comment]
Fixed as of https://github.com/nestjs/nest/pull/1594 :tada:
