### ISSUE TITLE
Nest-Router Adding Additional Slash before Controller

### ISSUE THREAD

**Issue by willcooley** [nestjsx/nest-router#53]
Issue:
In the Logs, when Nestjs goes to compile, an additional slash is being added before the module's controller. This can be verified by hitting the url route. If one were to go to `/api/v1/auth/`, you would get a 404, but the path in the url `/api/v1/auth//` works as a status 200.

**Terminal Log Path on Compiling:**
`[Nest] 21099   - 3/6/2019, 7:27:44 PM   [RoutesResolver] AuthController {/api/v1/auth//}: +0ms`

**What it should be:**
`[Nest] 21099   - 3/6/2019, 7:27:44 PM   [RoutesResolver] AuthController {/api/v1/auth/}: +0ms`

**Router Object:**
`

     // ROUTES
     const routes: Routes = [ {
		     path: '/api',
		     children: [ {
			path: '/v1',
			children: [
			     { path: '/auth', module: AuthModule }
		         ]
	             }]
	     }];

`

**Controller:**
`

     import { Controller } from '@nestjs/common';

     @Controller()
     export class AuthController {
 
       @Get()
       returnSomething() {}

     }

`

**Auth Module:**
`

     import { Module } from '@nestjs/common';

     // Controllers
     import { AuthController } from './auth.controller';

     @Module({
	    controllers: [ AuthController ]
     })
     export class AuthModule {}

`

**Comment by willcooley** [comment]
well.... I believe the issue has to deal with nestjs itself, and not nest-router after more debugging.... https://github.com/nestjs/nest/pull/1594 as mentioned in another ticket. I fixed nestjs router issue, and it works fine now; so I guess it's to wait until that ticket is closed and released. Basically, nestjs is adding a base path in on '/' if nothing is specified it seems, and the base and path when added are inverted possibly.

**Comment by willcooley** [comment]
for the interim, i used node package module called **patch-package**, and then fixed the file. After fixing the file, I ran the command `npx patch-package @nestjs/core` to patch it until it was fixed. 

https://www.npmjs.com/package/patch-package

**Comment by shekohex** [comment]
Yup, it's a bug in the nest core, and already reported to nestjs, and it's fixed, but not yet released.

I will hold this issue until Kamil release that version with the fix.

**Comment by shekohex** [comment]
I think this is also fixed as of https://github.com/nestjs/nest/pull/1594 :tada:
