### ISSUE TITLE
childrens !== 'children'

### ISSUE THREAD

**Issue by alsoicode** [nestjsx/nest-router#6]
Can you please change "childrens" to "children"? There's no such word as "childrens" in the English language :)

**Comment by shekohex** [comment]
Thanks @alsoicode,
it's now fixed in `v1.0.5` :tada: 
`childrens` is now deprecated, and will be removed around `v1.5.0`  
see [CHANGELOG](/shekohex/nest-router/blob/master/CHANGELOG.md)

**Comment by alsoicode** [comment]
Super! Can't wait to try this out.
