### ISSUE TITLE
Route gets double slash when try to define root level routes; `//users` instead of `/users`

### ISSUE THREAD

**Issue by takayukioda** [nestjsx/nest-router#72]
Is there any plan to support root level routing?
It seems not at the moment.

I was thinking of separating normal user namespace and admin user space like following, but got result of having `//users` as result where I expected to have `/users`. This `//users` is really accessible by `//users` and doesn't treated as `/users`.

It would be nice if I could manage all routes including root level in this route configuration.

route setting code

```ts
export const routes: Routes = [
  {
    path: '',
    children: [
      UserModule,
    ],
  },
  {
    path: 'admin',
    children: [
      AdminUserModule,
    ],
  },
]
```

part of log output

```
[RoutesResolver] UserController {//users}
[RoutesResolver] AdminUserController {/admin/users}
```

**Comment by shekohex** [comment]
It seems to me that is an internal problem with nest, it breaks again.
could you please try to add the slash ?
```ts
export const routes: Routes = [
  {
    path: '/',
    children: [
      UserModule,
    ],
  },
  {
    path: 'admin',
    children: [
      AdminUserModule,
    ],
  },
]
```
i don't tested that code, by the way could you also make sure that your controller is `'users'` without the slash ?
```ts
@Controller('users')
export class UserController {
  ...
}
```

I'm sure that my route validation is working perfectly, see:
https://github.com/nestjsx/nest-router/blob/0ba47962d9ba2af04cc1ab62c626a75b398eeb10/src/test/utils/validate-path.spec.ts#L16-L20

i would here the result, if it is so, i will mark this issue as a bug, and could you also please add more information about what version of nest, nest-router you use ?

**Comment by takayukioda** [comment]
Thanks for the feedback and suggestions!
Unfortunately, it still happens with your suggestions.

nest@6.3.1
nest-router@1.0.9

Here's the branch for reproducing the issue. It should be simplified enough that you can just run server and test it without any annoying steps.
https://github.com/takayukioda/reproduce-lab/tree/master/nest-router-double-slash

Please take a look and let me know if I have misconfiguration.

```
[Nest] 13995   - 2019-07-11 18:40   [NestFactory] Starting Nest application...
[Nest] 13995   - 2019-07-11 18:40   [InstanceLoader] AppModule dependencies initialized +15ms
[Nest] 13995   - 2019-07-11 18:40   [InstanceLoader] RouterModule dependencies initialized +8ms
[Nest] 13995   - 2019-07-11 18:40   [InstanceLoader] UserModule dependencies initialized +1ms
[Nest] 13995   - 2019-07-11 18:40   [InstanceLoader] AdminUserModule dependencies initialized +1ms
[Nest] 13995   - 2019-07-11 18:40   [RoutesResolver] UserController {//users}: +8ms
[Nest] 13995   - 2019-07-11 18:40   [RouterExplorer] Mapped {/, GET} route +2ms
[Nest] 13995   - 2019-07-11 18:40   [RoutesResolver] AdminUserController {/admin/users}: +1ms
[Nest] 13995   - 2019-07-11 18:40   [RouterExplorer] Mapped {/, GET} route +1ms
[Nest] 13995   - 2019-07-11 18:40   [NestApplication] Nest application successfully started +3ms
::1 - - [1562838031918] "GET / localhost 404" 2ms
::1 - - [1562838038181] "GET /admin/users localhost 200" 7ms
::1 - - [1562838041270] "GET //users localhost 200" 1ms
::1 - - [1562838053142] "GET /users localhost 404" 0ms
```

**Comment by micalevisk** [comment]
This doesn't happen anymore in Nest v8, only in v6 and v7.

```
[Nest] 41672  - 09/06/2021, 3:59:09 PM     LOG [NestFactory] Starting Nest application...
[Nest] 41672  - 09/06/2021, 3:59:09 PM     LOG [InstanceLoader] AppModule dependencies initialized +21ms
[Nest] 41672  - 09/06/2021, 3:59:09 PM     LOG [InstanceLoader] RouterModule dependencies initialized +0ms
[Nest] 41672  - 09/06/2021, 3:59:09 PM     LOG [InstanceLoader] UserModule dependencies initialized +1ms
[Nest] 41672  - 09/06/2021, 3:59:09 PM     LOG [InstanceLoader] AdminUserModule dependencies initialized +7ms
[Nest] 41672  - 09/06/2021, 3:59:09 PM     LOG [RoutesResolver] UserController {/users}: +6ms
[Nest] 41672  - 09/06/2021, 3:59:09 PM     LOG [RouterExplorer] Mapped {/users, GET} route +2ms
[Nest] 41672  - 09/06/2021, 3:59:09 PM     LOG [RoutesResolver] AdminUserController {/admin/users}: +0ms
[Nest] 41672  - 09/06/2021, 3:59:09 PM     LOG [RouterExplorer] Mapped {/admin/users, GET} route +1ms
[Nest] 41672  - 09/06/2021, 3:59:09 PM     LOG [NestApplication] Nest application successfully started +1ms
::ffff:127.0.0.1 - - [1630958353012] "GET //users localhost 404" 5ms
::ffff:127.0.0.1 - - [1630958355615] "GET /users localhost 200" 1ms
```

**Comment by shekohex** [comment]
That's great!
I guess that's because they included now the Router Module into the core in v8 maybe?

**Comment by micalevisk** [comment]
I think so.

Just find the line that has this bug (in v7): https://github.com/nestjs/nest/blob/98eee426df5514b2194f50c9a81d8d9ac1540b55/packages/core/router/router-explorer.ts#L100

**Comment by shekohex** [comment]
So we should mark this as solved now.

So, anyone has this issue, Please upgrade to Nestjs v8.
