### ISSUE TITLE
Lack of documentation

### ISSUE THREAD

**Issue by vdpdev** [nestjsx/nest-router#75]
Could you create more complex example of usage your router, please?
For example
Prefix 'api/v1'
public route
PostsModule -> view post
private route
PostsModule -> sendPost

Thank you in advance!

**Comment by IzioDev** [comment]
Hi, the package isn't designed to manage the authorizations.

I use it for example to separate my API versions.


But, you can create two separate module, one could be `public` (no authorization) and the other could be `private`, but it has to be two separate module, you cannot go granular with controller method (and in fact it would be super messy to maintain this).
