### ISSUE TITLE
Nest Router in V5

### ISSUE THREAD

**Issue by thaoula** [nestjsx/nest-router#8]
Hi @shekohex,

Do you know if the nest-router package works in V5?

We are are trying upgrade application and we are having issues in our authentication middleware.

In v4, req.path = the full relative path to an item eg /api/private/users
In v5, req.path = "/"

resolve(...excluded: Route[]): FunctionMiddleware {
        return (req, res, next) => {
            const isExcluded = excluded.filter(route => {
                let excluedPath = route.path == **req.path;**
                return excluedPath
            }).length > 0;
}}

Not sure if this is a Nest issue or a router issue.

Regards,
Tarek

**Comment by shekohex** [comment]
Hi @thaoula :grinning: 

Actually The `RouterModule` **Should Work** as Expected  with the  new Version of Nest `v5`

I also added an example to demonstrate that it works as usual
check it [here](/shekohex/nest-router/tree/master/examples/nest-v5x)

and about your issue I also added a `LoggerMiddleware` that works like a charm.
 see it also [LoggerMiddleware](/shekohex/nest-router/blob/master/examples/nest-v5x/src/logger.middleware.ts#L17)

**Comment by thaoula** [comment]
Hi @shekohex,

Really appreciate getting back to me and thanks for the example.

I was getting -

![image](https://user-images.githubusercontent.com/349133/39160643-9cf1144a-4796-11e8-9af0-62a4fc22044a.png)

Then I changed forRoutes("*") to forRoutes("/") like you example and now it works.

Regards,
Tarek

**Comment by shekohex** [comment]
Glad it works.
Happy Coding :smile: !

**Comment by thaoula** [comment]
Actually, do you mind explaining the difference between forRoutes("*") and forRoutes("/"). Our application has a number of middleware registered like this.

It would be great to understand why it worked in V4 and not V5.

**Comment by shekohex** [comment]
Imo, i think because of this note
> move from traditional express middleware model: each middleware is solely bounded to a particular path, regardless of the request method.


Nest Now not only supporting Express Middleware Model, Actually the design had to be changed to work well with new Adapters.
but anyway i think by just setting a global middleware in the root module. it should catch all routes, did you try this ? give it a shot.

**Comment by johnbendi** [comment]
@shekohex your `Note` link is broken!

**Comment by shekohex** [comment]
@johnbendi
Thanks, Comment updated :)
