### ISSUE TITLE
Question : What are the drawbacks of having route prefix at controller level instead of module level ?

### ISSUE THREAD

**Issue by Kannas24** [nestjsx/nest-router#84]
It scratched my head many times and I also tried to find the information on web but nothing answered my question so I'm finally posting it here.

Are there any drawbacks of adding version information to the controller itself instead of doing it to the module level ?

**Sample code**

```
@Controller("v1/user")
UserV1Controller
{
    @Get("profile")
     userProfile()
       {
       }
}

@Controller("v2/user")
UserV2Controller
{
    @Get("profile")
     userProfile()
       {
       }
}

**In module**
@Module({
  controllers:[UserV1Controller, UserV2Controller],
})
```

**Different routes** 

v1/user/profile
v2/user/profile

PS: I'm not questioning the existence of nest-route package, I find it amazing and appreciate the effort and knowledge used in implementing this. My question is specific to api versioning only.

**Comment by vahidvdn** [comment]
@shekohex Any idea on this?

**Comment by shekohex** [comment]
I guess there are no difference, unless you are using  Controllers for other things like microservices/websockets .. etc.

So yeah unless you don't want your code organized in the same way you organize your modules (that's what this package do) you could go for your case of course, but imo that dose not scale well, especially if you have too many controllers.
